### ISSUE TITLE
Neispravna poveznica na sliku u README.md ?

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/Li-ion-charger-BQ24295-with-5V-USB-output-board-hardware-design#1]
https://github.com/SolderedElectronics/Li-ion-charger-BQ24295-with-5V-USB-output-board-hardware-design/blob/7294943773bb3a7f665f644393ce3a54e7380dfc/README.md?plain=1#L5C54-L5C201

umjesto:

https://github.com/SolderedElectronics/Li-ion-charger-BQ24295-with-5V-USB-output-board-hardware-design/blob/main/OUTPUTS/V1.1.1/333075.jpg?raw=true

čini mi se da bi trebalo biti:

https://github.com/SolderedElectronics/Li-ion-charger-BQ24295-with-5V-USB-output-board-hardware-design/blob/main/OUTPUTS/V1.0.0/333075.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
